# Generated by Django 3.2.4 on 2021-06-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='HeroSection',
        ),
    ]
