# Generated by Django 3.2.4 on 2021-06-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='services/')),
                ('category', models.CharField(choices=[('mep', 'mep'), ('contracting', 'contracting')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonaial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personname', models.CharField(max_length=50)),
                ('personprofession', models.CharField(max_length=50)),
                ('testimonial', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='testimonial/')),
            ],
        ),
    ]
