# Generated by Django 3.2.4 on 2021-06-21 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_service_testimonaial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonaial',
            new_name='Testimonial',
        ),
    ]
