# Generated by Django 3.2.4 on 2021-06-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_about_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.CharField(default='gegc2010@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='mobileno',
            field=models.CharField(default=971544568754, max_length=50),
        ),
    ]
