# Generated by Django 3.2.4 on 2021-06-09 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_advantages_services_testimonial_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='personphoto',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/works/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
