# Generated by Django 3.2.4 on 2021-06-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_auto_20210623_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('blogbody', models.CharField(max_length=4000)),
                ('blogthumbnail', models.ImageField(upload_to='blogthumbnail/')),
            ],
        ),
    ]
