# Generated by Django 3.2.4 on 2021-06-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_testimonial_personphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='personphoto',
            field=models.ImageField(upload_to='media/testimonials/%Y/%m/%d'),
        ),
    ]
