# Generated by Django 3.2.4 on 2021-06-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_alter_testimonial_personphoto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advantages',
            new_name='Advantage',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RenameModel(
            old_name='Works',
            new_name='Work',
        ),
    ]
