# Generated by Django 3.2.4 on 2021-06-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companylogo', models.ImageField(upload_to='companylogo/')),
                ('companyname', models.CharField(max_length=100)),
            ],
        ),
    ]
