# Generated by Django 3.2.4 on 2021-06-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_auto_20210609_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='photo',
            field=models.ImageField(upload_to='media/about/'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='photo',
            field=models.ImageField(upload_to='media/advantages/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='photo',
            field=models.ImageField(upload_to='media/hero/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.ImageField(upload_to='media/services/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='personphoto',
            field=models.ImageField(upload_to='media/testimonials/'),
        ),
        migrations.AlterField(
            model_name='work',
            name='photo',
            field=models.ImageField(upload_to='media/works/'),
        ),
    ]
