# Generated by Django 3.2.4 on 2021-06-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_auto_20210609_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='photo',
            field=models.ImageField(upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='photo',
            field=models.ImageField(upload_to='advantages/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='photo',
            field=models.ImageField(upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.ImageField(upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='personphoto',
            field=models.ImageField(upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='work',
            name='photo',
            field=models.ImageField(upload_to='works/'),
        ),
    ]
