# Generated by Django 3.2.4 on 2021-06-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_alter_about_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('completed', 'completed'), ('running', 'running'), ('majorprojects', 'majorprojects')], default='completed', max_length=40),
        ),
    ]
