# Generated by Django 3.2.4 on 2021-06-24 09:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0009_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogwriter',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogwriterinfo',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogwriterphoto',
            field=models.ImageField(default=None, upload_to='blogwriterphoto/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blogbody',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
