# Generated by Django 3.2.4 on 2021-06-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0010_auto_20210624_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogsubtitle',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
