# Generated by Django 3.2.4 on 2021-06-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0011_blog_blogsubtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogsubtitle',
            field=models.CharField(default='subitle', max_length=2000),
        ),
    ]
