# Generated by Django 3.2.4 on 2021-06-24 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0012_alter_blog_blogsubtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blogsubtitle',
            field=models.CharField(default='blog subtitle', max_length=2000),
        ),
    ]
