# Generated by Django 3.2.4 on 2021-06-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0014_expertworker_qyalitywork_support'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QyalityWork',
            new_name='QualityWork',
        ),
    ]
