# Generated by Django 3.2.4 on 2021-07-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0015_rename_qyalitywork_qualitywork'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=4000)),
                ('photo', models.ImageField(upload_to='aboutmore/')),
            ],
        ),
    ]
