# Generated by Django 3.2.4 on 2021-07-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0017_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='mobileno',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
