# Generated by Django 3.2.5 on 2021-07-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0019_clientscount_completedprojectcount_experworkercount_runningprojectcount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExperWorkerCount',
            new_name='ExpertWorkerCount',
        ),
    ]
