# Generated by Django 3.2.5 on 2021-07-15 12:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0020_rename_experworkercount_expertworkercount'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='finishingdate',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='mainclient',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='startingdate',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
