# Generated by Django 3.2.5 on 2021-07-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0021_auto_20210715_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finishingdate',
            field=models.CharField(default='30/1/2020', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(default='location', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='mainclient',
            field=models.CharField(default='clientname', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='startingdate',
            field=models.CharField(default='27/2/2018', max_length=100),
        ),
    ]
