# Generated by Django 3.2.5 on 2021-07-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0024_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finishingdate',
            field=models.CharField(default='30/1/2020', max_length=100, null=True),
        ),
    ]
