# Generated by Django 3.2.5 on 2021-07-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0025_alter_project_finishingdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='finishingdate',
        ),
    ]
