# Generated by Django 3.2.5 on 2021-07-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0026_remove_project_finishingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='finishingdate',
            field=models.CharField(default='30/1/2020', max_length=100),
        ),
    ]
