# Generated by Django 3.2.5 on 2021-07-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0027_project_finishingdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='finishingdate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mainclient',
        ),
        migrations.RemoveField(
            model_name='project',
            name='startingdate',
        ),
    ]
