# Generated by Django 3.2.5 on 2021-07-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0028_auto_20210715_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
    ]
